### ISSUE TITLE
[ros2] Diagnostics aggregator base path

### ISSUE THREAD

**Issue by Noel215** [ros/diagnostics#303]
Hi,

With a diagnostic named `led1`:
```
analyzers:
  ros__parameters:
    path: Aggregator
    hardware:
      type: 'diagnostic_aggregator/GenericAnalyzer'
      path: Hardware
      startswith: [ 'led' ]
```

The name for that diagnostic  in the topic `/diagnostics_agg`  would be `/Aggregator/Hardware/led1` 

However, if I don't set the base path:
```
analyzers:
  ros__parameters:
    hardware:
      type: 'diagnostic_aggregator/GenericAnalyzer'
      path: Hardware
      startswith: [ 'led' ]
```
The name would be `//Hardware/led1`.
With the same case in ROS, the name would be `/Hardware/led1`

Is there any reason why the default `base_path` for the Diagnostics Aggregator in ROS 2 is `/`?
