### ISSUE TITLE
Operation level from diagnostic_aggregator not consistent

### ISSUE THREAD

**Issue by 130s** [ros/diagnostics#4]
Though very rarely, I've seen /diagnostic_agg msgs like below. Look at "level". Level of /Devices/IMU is 2 (ie. ERROR) but all of its sub devices show level 0 (OK).

(At Willow, you may be able to reproduce with prl).

```
    level: 2
    name: /Devices/IMU
    message: Expected 4, found 3
    hardware_id: ''
    values: 
      - 
        key: imu_node: Calibration Status
        value: Gyro is calibrated
      - 
        key: imu_node: Frequency Status
        value: Desired frequency met
      - 
        key: imu_node: IMU Status
        value: IMU is running
  - 
    level: 0
    name: /Devices/IMU/Calibration Status
    message: Gyro is calibrated
    hardware_id: Inertia-Link_4200-4132
    values: 
      - 
        key: X bias
        value: -0.0105521
      - 
        key: Y bias
        value: -0.0115087
      - 
        key: Z bias
        value: 0.00218787
  - 
    level: 0
    name: /Devices/IMU/Frequency Status
    message: Desired frequency met
    hardware_id: Inertia-Link_4200-4132
    values: 
      - 
        key: Events in window
        value: 503
      - 
        key: Events since startup
        value: 4802787
      - 
        key: Duration of window (s)
        value: 5.029089
      - 
        key: Actual frequency (Hz)
        value: 100.018110
      - 
        key: Target frequency (Hz)
        value: 100.000000
      - 
        key: Minimum acceptable frequency (Hz)
        value: 95.000000
      - 
        key: Maximum acceptable frequency (Hz)
        value: 105.000000
  - 
    level: 0
    name: /Devices/IMU/IMU Status
    message: IMU is running
    hardware_id: Inertia-Link_4200-4132
    values: 
      - 
        key: Device
        value: /etc/ros/sensors/imu
      - 
        key: TF frame
        value: imu_link
      - 
        key: Error count
        value: 0
      - 
        key: Excessive delay
        value: 0
```

diagnostic from debian ros-groovy-diagnostic-aggregator/precise uptodate 1.7.7-0precise-20121205-0830-+0000
