### ISSUE TITLE
GenericAnalyzer also removes prefix from path

### ISSUE THREAD

**Issue by Karsten1987** [ros/diagnostics#44]
I am not sure, if this is a real issue or something I am doing wrong.

My config is as follows:
```
pub_rate: 1.0
base_path: ""
analyzers:
   lasers:
     type: GenericAnalyzer
     path: Laser
     find_and_remove_prefix: 'Laser'
```

What I see in my robot_monitor is that all information about laser is published inside the '/' namespace. 

When I then change the config to this: (please note the change from `Laser` to `laser`)
```
pub_rate: 1.0
base_path: ""
analyzers:
   lasers:
     type: GenericAnalyzer
     path: Laser
     find_and_remove_prefix: 'laser'
```

Everything gets published as expected, saying the category is called `Laser` and all messages are trimmed without the `laser` prefix.

Can anybody confirm that?
