### ISSUE TITLE
Stale items are not ignored with discard_stale: true when no status has been published at all

### ISSUE THREAD

**Issue by stwirth** [ros/diagnostics#65]
With a configuration like this
```
analyzers:
  my_stale_item:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Nonexistent1
    find_and_remove_prefix: 'nonexistent1'
  my_stale_item_that_should_be_ignored:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Nonexistent2
    find_and_remove_prefix: 'nonexistent2'
    discard_stale: true
    timeout: 5.0
```
and with no messages published on `/diagnostics`, I would expect "Nonexistent1" to show up as stale and "Nonexistent2" to *not* show up in `/diagnostics_agg`.

However, both are always present in `/diagnostics_agg`.
Here's a minimal launch file to reproduce:
```XML
<launch>

  <node pkg="diagnostic_aggregator" type="aggregator_node" name="diagnostic_aggregator">
    <rosparam>
      analyzers:
        my_stale_item:
          type: diagnostic_aggregator/GenericAnalyzer
          path: Nonexistent1
          find_and_remove_prefix: 'nonexistent1'
        my_stale_item_that_should_be_ignored:
          type: diagnostic_aggregator/GenericAnalyzer
          path: Nonexistent2
          find_and_remove_prefix: 'nonexistent2'
          discard_stale: true
          timeout: 5.0
    </rosparam>
  </node>

  <node name="$(anon monitor)" pkg="rqt_robot_monitor" type="rqt_robot_monitor"/>

</launch>
```
