### ISSUE TITLE
Adding Key/Value pairs to diagnostic messages that are specified in the analyzer yaml file. 

### ISSUE THREAD

**Issue by nnarain-cpr** [ros/diagnostics#80]
Any way to, or interest in, being able to add key/value pairs to diagnostic status messages that are specified in the analyzer yaml file. I basically want to "tag" a group of diagnostic messages and use that information in some later processing.

Something like the following:

```yaml
analyzers:
  battery:
    type: ...
    path: ...
    find_and_remove_prefix: ...
    tags:
      - key1: value1
      - key2: value2
```
